name: Deploy CSApp to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t csapp:1.0.1 .

      - name: Save Docker image
        run: docker save csapp:1.0.1 | gzip > csapp.tar.gz

      - name: Transfer Docker image to ECS
        run: |
          sshpass -p "${{ secrets.HUAWEI_SERVER_PASSWORD }}" scp csapp.tar.gz ubuntu@${{ secrets.HUAWEI_SERVER_IP }}:/tmp/

      - name: Deploy Docker container on ECS
        run: |
          sshpass -p "${{ secrets.HUAWEI_SERVER_PASSWORD }}" ssh ubuntu@${{ secrets.HUAWEI_SERVER_IP }} << 'EOF'
          sudo docker load < /tmp/csapp.tar.gz
          sudo docker stop csapp || true
          sudo docker rm csapp || true
          sudo docker run -d -p 5000:5000 --name csapp csapp:1.0.1
          EOF
#1