name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push-swr-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Login to Huawei SWR
        env:
          HUAWEI_CLOUD_ACCOUNT: ${{ secrets.HUAWEI_CLOUD_ACCOUNT }}
          HUAWEI_CLOUD_PASSWORD: ${{ secrets.HUAWEI_CLOUD_PASSWORD }}
          HUAWEI_CLOUD_REGION: ${{ secrets.HUAWEI_CLOUD_REGION }}
        run: |
          echo $HUAWEI_CLOUD_PASSWORD | docker login -u $HUAWEI_CLOUD_ACCOUNT --password-stdin swr.${HUAWEI_CLOUD_REGION}.myhuaweicloud.com

      - name: Build, tag, and push image to Huawei SWR
        env:
          HUAWEI_CLOUD_REGION: ${{ secrets.HUAWEI_CLOUD_REGION }}
          SWR_REPOSITORY: ${{ secrets.HUAWEI_SWR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t swr.${HUAWEI_CLOUD_REGION}.myhuaweicloud.com/$SWR_REPOSITORY:$IMAGE_TAG .
          docker push swr.${HUAWEI_CLOUD_REGION}.myhuaweicloud.com/$SWR_REPOSITORY:$IMAGE_TAG

      - name: Pull latest images
        env:
          HUAWEI_CLOUD_REGION: ${{ secrets.HUAWEI_CLOUD_REGION }}
          SWR_REPOSITORY: ${{ secrets.HUAWEI_SWR_REPOSITORY }}
        run: |
          docker pull swr.${HUAWEI_CLOUD_REGION}.myhuaweicloud.com/$SWR_REPOSITORY:latest
